# backend/render.yaml
services:
  - type: web
    name: nodecanvas-backend01
    runtime: node
    buildCommand: npm install
    startCommand: node server.cjs
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
